/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MerchantDirectoryLinkDTO {
  'urlTemplate': string;
  'estimatedCpc'?: number;
  'mobileEstimatedCpc'?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'urlTemplate',
      baseName: 'urlTemplate',
      type: 'string',
    },
    {
      name: 'estimatedCpc',
      baseName: 'estimatedCpc',
      type: 'number',
    },
    {
      name: 'mobileEstimatedCpc',
      baseName: 'mobileEstimatedCpc',
      type: 'number',
    },
  ];

  static getAttributeTypeMap() {
    return MerchantDirectoryLinkDTO.attributeTypeMap;
  }
}
