/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MerchantVisibilityChangesData } from './merchantVisibilityChangesData';

export class MerchantVisibilityChangesDetails {
  'activatedMerchants': Array<MerchantVisibilityChangesData>;
  'deactivatedMerchants': Array<MerchantVisibilityChangesData>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'activatedMerchants',
      baseName: 'activatedMerchants',
      type: 'Array<MerchantVisibilityChangesData>',
    },
    {
      name: 'deactivatedMerchants',
      baseName: 'deactivatedMerchants',
      type: 'Array<MerchantVisibilityChangesData>',
    },
  ];

  static getAttributeTypeMap() {
    return MerchantVisibilityChangesDetails.attributeTypeMap;
  }
}
