/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PrivateMetaInformationDTO {
  'name': string;
  'version': string;
  'gitHeadLink'?: string;
  'builtAt'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'version',
      baseName: 'version',
      type: 'string',
    },
    {
      name: 'gitHeadLink',
      baseName: 'gitHeadLink',
      type: 'string',
    },
    {
      name: 'builtAt',
      baseName: 'builtAt',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return PrivateMetaInformationDTO.attributeTypeMap;
  }
}
