/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RequestStatus {
  'country': string;
  'requestId': string;
  'startedAt': number;
  'lastUpdate': number;
  'offersSentToClient': number;
  'format': string;
  'tokenId': string;
  'trackingId': number;
  'categoryId'?: object;
  'merchantId'?: object;
  'partNumber': string;
  'duration': number;
  'snapOffersPerSecond'?: object;
  'averageOffersPerSecond'?: object;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'country',
      baseName: 'country',
      type: 'string',
    },
    {
      name: 'requestId',
      baseName: 'requestId',
      type: 'string',
    },
    {
      name: 'startedAt',
      baseName: 'startedAt',
      type: 'number',
    },
    {
      name: 'lastUpdate',
      baseName: 'lastUpdate',
      type: 'number',
    },
    {
      name: 'offersSentToClient',
      baseName: 'offersSentToClient',
      type: 'number',
    },
    {
      name: 'format',
      baseName: 'format',
      type: 'string',
    },
    {
      name: 'tokenId',
      baseName: 'tokenId',
      type: 'string',
    },
    {
      name: 'trackingId',
      baseName: 'trackingId',
      type: 'number',
    },
    {
      name: 'categoryId',
      baseName: 'categoryId',
      type: 'object',
    },
    {
      name: 'merchantId',
      baseName: 'merchantId',
      type: 'object',
    },
    {
      name: 'partNumber',
      baseName: 'partNumber',
      type: 'string',
    },
    {
      name: 'duration',
      baseName: 'duration',
      type: 'number',
    },
    {
      name: 'snapOffersPerSecond',
      baseName: 'snapOffersPerSecond',
      type: 'object',
    },
    {
      name: 'averageOffersPerSecond',
      baseName: 'averageOffersPerSecond',
      type: 'object',
    },
  ];

  static getAttributeTypeMap() {
    return RequestStatus.attributeTypeMap;
  }
}
