/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConstraintsAtProfileLevel } from './constraintsAtProfileLevel';
import { Duration } from './duration';
import { SearchMetadata } from './searchMetadata';

export class SearchDebugMetadata {
  'step': string;
  'message': string;
  'success': boolean;
  'details'?: string;
  'constraints'?: ConstraintsAtProfileLevel;
  'trafficGroup'?: string;
  'searchMetadata': Array<SearchMetadata>;
  'duration'?: Duration;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'step',
      baseName: 'step',
      type: 'string',
    },
    {
      name: 'message',
      baseName: 'message',
      type: 'string',
    },
    {
      name: 'success',
      baseName: 'success',
      type: 'boolean',
    },
    {
      name: 'details',
      baseName: 'details',
      type: 'string',
    },
    {
      name: 'constraints',
      baseName: 'constraints',
      type: 'ConstraintsAtProfileLevel',
    },
    {
      name: 'trafficGroup',
      baseName: 'trafficGroup',
      type: 'string',
    },
    {
      name: 'searchMetadata',
      baseName: 'searchMetadata',
      type: 'Array<SearchMetadata>',
    },
    {
      name: 'duration',
      baseName: 'duration',
      type: 'Duration',
    },
  ];

  static getAttributeTypeMap() {
    return SearchDebugMetadata.attributeTypeMap;
  }
}
