/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FieldCount } from './fieldCount';
import { FieldStats } from './fieldStats';

export class SearchMetadata {
  'solrQuery': string;
  'numberOfOffers': number;
  'numberOfHiddenOffers': number;
  'hasSynonyms': boolean;
  'responseTime': number;
  'fieldStats'?: { [key: string]: FieldStats };
  'facetCountsFields'?: { [key: string]: Array<FieldCount> };
  'facetCountsIntervals'?: { [key: string]: Array<FieldCount> };

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'solrQuery',
      baseName: 'solrQuery',
      type: 'string',
    },
    {
      name: 'numberOfOffers',
      baseName: 'numberOfOffers',
      type: 'number',
    },
    {
      name: 'numberOfHiddenOffers',
      baseName: 'numberOfHiddenOffers',
      type: 'number',
    },
    {
      name: 'hasSynonyms',
      baseName: 'hasSynonyms',
      type: 'boolean',
    },
    {
      name: 'responseTime',
      baseName: 'responseTime',
      type: 'number',
    },
    {
      name: 'fieldStats',
      baseName: 'fieldStats',
      type: '{ [key: string]: FieldStats; }',
    },
    {
      name: 'facetCountsFields',
      baseName: 'facetCountsFields',
      type: '{ [key: string]: Array<FieldCount>; }',
    },
    {
      name: 'facetCountsIntervals',
      baseName: 'facetCountsIntervals',
      type: '{ [key: string]: Array<FieldCount>; }',
    },
  ];

  static getAttributeTypeMap() {
    return SearchMetadata.attributeTypeMap;
  }
}
