/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ShoppingFeedsExplainQuota {
  'limit': number;
  'consumed': number;
  'instantOfAggregation': number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'limit',
      baseName: 'limit',
      type: 'number',
    },
    {
      name: 'consumed',
      baseName: 'consumed',
      type: 'number',
    },
    {
      name: 'instantOfAggregation',
      baseName: 'instantOfAggregation',
      type: 'number',
    },
  ];

  static getAttributeTypeMap() {
    return ShoppingFeedsExplainQuota.attributeTypeMap;
  }
}
