/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ShoppingOfferFlags {
  'offensiveContent'?: object;
  'greenProduct'?: object;
  'saleEvent'?: object;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'offensiveContent',
      baseName: 'offensiveContent',
      type: 'object',
    },
    {
      name: 'greenProduct',
      baseName: 'greenProduct',
      type: 'object',
    },
    {
      name: 'saleEvent',
      baseName: 'saleEvent',
      type: 'object',
    },
  ];

  static getAttributeTypeMap() {
    return ShoppingOfferFlags.attributeTypeMap;
  }
}
