/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ShoppingOfferImageUrl {
  'url'?: string;
  'zoomUrl'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'url',
      baseName: 'url',
      type: 'string',
    },
    {
      name: 'zoomUrl',
      baseName: 'zoomUrl',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return ShoppingOfferImageUrl.attributeTypeMap;
  }
}
