/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ShoppingOfferUrls {
  'landingUrl'?: string;
  'mobileLandingUrl'?: string;
  'trackedUrl'?: string;
  'mobileTrackedUrl'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'landingUrl',
      baseName: 'landingUrl',
      type: 'string',
    },
    {
      name: 'mobileLandingUrl',
      baseName: 'mobileLandingUrl',
      type: 'string',
    },
    {
      name: 'trackedUrl',
      baseName: 'trackedUrl',
      type: 'string',
    },
    {
      name: 'mobileTrackedUrl',
      baseName: 'mobileTrackedUrl',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return ShoppingOfferUrls.attributeTypeMap;
  }
}
