/**
 * Shopping API
 * KelkooGroup next generation shopping API. Documentation available at https://developers.kelkoogroup.com/.
 *
 * The version of the OpenAPI document: 4.21.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Duration } from './duration';

export class TemporalUnit {
  'dateBased': boolean;
  'timeBased': boolean;
  'duration': Duration;
  'durationEstimated': boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'dateBased',
      baseName: 'dateBased',
      type: 'boolean',
    },
    {
      name: 'timeBased',
      baseName: 'timeBased',
      type: 'boolean',
    },
    {
      name: 'duration',
      baseName: 'duration',
      type: 'Duration',
    },
    {
      name: 'durationEstimated',
      baseName: 'durationEstimated',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return TemporalUnit.attributeTypeMap;
  }
}
